project:
  name: "fine_tune_research"
  
dataset:  
  type: "hf"
  name: "Clinton/Text-to-sql-v1"
  format: "text"

model:
  base:
    type: "hf"
    name: "meta-llama/Llama-2-7b-hf"
  output:
    type: "hf"
    name: "rparundekar/llama2-7b-text-to-sql"

training:
  trainer:
    packing: True
    max_seq_length: 512
  sft:
    per_device_train_batch_size: 20
    per_device_eval_batch_size: 20
    fp16: False
    learning_rate: 0.0002
    lr_scheduler_type: "cosine"
    warmup_ratio: 0.1
    num_train_epochs: 1
    save_strategy: "epoch"
    gradient_accumulation_steps: 4
    gradient_checkpointing: True
    gradient_checkpointing_kwargs:
      use_reentrant: False
    logging_strategy: "steps"
    logging_steps: 5
  other:
    freeze_embed: True
    n_freeze: 24