# env configuration
env: "test"

# Defaults
base_model_name: "tiiuae/falcon-7b"
dataset_name: "heliosbrahma/mental_health_chatbot_dataset"
dataset_training_column: "text"
output_model_name: "sadmoseby/falcoln-7b-peft-train-intermediate"

# Training Configuation
config_suffix: "config"
peft_config_path: "/mnt/config/peft"
training_config_path: "/mnt/config/training"
bnb_config_path: "/mnt/config/bnb"

# Directories For Pretrained Model, Checkpoint, and Dataset
model_mount_path: "/mnt/models"
checkpoint_path: "/mnt/checkpoint"
dataset_mount_path: "/mnt/datasets"
