apiVersion: batch/v1
kind: Job
metadata:
  name: peft-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      subdomain: peft-svc # has to match Service name
      restartPolicy: Never
      containers:
      - name: peft
        image: rparundekar/fine_tune_research:latest
        command:
        - bash
        - "-c"
        - "python app.py"
        ## OR
        # - bash
        # - "-c"
        # - "sleep 3600"
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wandb-api-key
        - name: WANDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wandb-username
        - name: WANDB_PROJECT
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wandb-project
        - name: WANDB_MODE
          valueFrom:
            secretKeyRef:
              name: secrets
              key: wandb-mode
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: hf-token

        {% if model_name %}
        - name: model_name
          value: {{ model_name }}
        {% endif %}

        {% if dataset_name %}
        - name: dataset_name
          value: {{ dataset_name }}
        {% endif %}

        {% if dataset_training_column %}
        - name: dataset_training_column
          value:  {{ dataset_training_column }}
        {% endif %}

        {% if checkpoint_model_hf_path %}
        - name: checkpoint_model_hf_path
          value: {{ checkpoint_model_hf_path}}
        {% endif %}

        volumeMounts:
          - mountPath: "/mnt/config/peft"
            name: peft-config
            readOnly: true
          - mountPath: "/mnt/config/training"
            name: training-config
            readOnly: true
      volumes:
        - name: peft-config
          configMap:
            name: peft
        - name: training-config
          configMap:
            name: training
