apiVersion: v1
kind: ConfigMap
metadata:
  name: peft 
data:
  config: |
    lora_alpha: 16
    lora_dropout: 0.1
    r: 64
    bias: "none"
    task_type: "CAUSAL_LM"
    target_modules:
        - "query_key_value"
        - "dense"
        - "dense_h_to_4h"
        - "dense_4h_to_h"
