apiVersion: batch/v1
kind: Job
metadata:
  name: peft-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      subdomain: peft-svc # has to match Service name
      restartPolicy: Never
      containers:
      - name: peft
        image: rparundekar/fine_tune_research:latest
        command:
        - python
        - "./app.py"
        ## OR
        # - bash
        # - "-c"
        # - "sleep 3600"
        env:
        - name: WANDB_MODE
          value: disabled 
        - name: model_name
          value: "tiiuae/falcon-7b"
        - name: dataset_name
          value: "heliosbrahma/mental_health_chatbot_dataset"
        - name: dataset_training_column
          value: text
        volumeMounts:
          - mountPath: "/mnt/config/peft"
            name: peft-config
            readOnly: true
          - mountPath: "/mnt/config/training"
            name: training-config
            readOnly: true
      volumes:
        - name: peft-config
          configMap:
            name: peft
        - name: training-config
          configMap:
            name: training
